config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  require 'resque/server'
  mount Resque::Server, at: '/resque'
  mount ActionCable.server => '/cable'
  resources :policies
  resources :companies
  resources :employees
  resources :bulk_employee_uploads do
    member do
      get 'employees' => 'bulk_employee_uploads#employees_index', as: :employees
      get 'errors' => 'bulk_employee_uploads#errors_index', as: :errors
      get 'errors/generate_csv' => 'bulk_employee_uploads#generate_csv', as: :generate_csv
    end
  end

  root to: 'bulk_employee_uploads#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bulk_employee_upload.rb
class BulkEmployeeUpload < ApplicationRecord
    mount_uploader :file, BulkEmployeeFileUploader
    belongs_to :company
    validates_with EmployeeCsvValidator

    after_create :start_create_employee_job

    def start_create_employee_job
        CreateEmployeeJob.perform_later(self)
    end

    def to_csv
        require 'csv'
        CSV.generate(headers: true) do |csv|
            attributes = ["Employee Name", "Email", "Phone", "Report To", "Assigned Policies"]
            upload_errors = EmpTempStorageError.where(bulk_employee_upload_id: self.id).map{|i| JSON.parse(i.data).with_indifferent_access }
            csv << attributes
            upload_errors.each do |car|
                csv << attributes.map{|i| i.parameterize.underscore}.map{ |attr| car[attr] }
            end
        end
    end
end

app/controllers/bulk_employee_uploads_controller.rb
class BulkEmployeeUploadsController < ApplicationController
  before_action :set_bulk_employee_upload, only: [:show, :edit, :update, :destroy, :employees_index, :errors_index, :generate_csv]

  # GET /bulk_employee_uploads
  # GET /bulk_employee_uploads.json
  def index
    @bulk_employee_uploads = BulkEmployeeUpload.all
  end

  # GET /bulk_employee_uploads/1
  # GET /bulk_employee_uploads/1.json
  def show
    @employee_count = Employee.where(bulk_employee_upload_id: @bulk_employee_upload.id).size
    @err_count = EmpTempStorageError.where(bulk_employee_upload_id: @bulk_employee_upload.id).size
    @total = @employee_count + @err_count
  end

  # GET /bulk_employee_uploads/new
  def new
    @bulk_employee_upload = BulkEmployeeUpload.new
    @companies = Company.all
  end

  # GET /bulk_employee_uploads/1/edit
  def edit
    @companies = Company.all
  end

  # GET /bulk_employee_uploads/1/employees
  def employees_index
    @employees = Employee.where(bulk_employee_upload_id: @bulk_employee_upload.id)
  end

  # GET /bulk_employee_uploads/1/errors
  def errors_index
    @errors = EmpTempStorageError.where(bulk_employee_upload_id: @bulk_employee_upload.id)
    @employees = []
    @errors.each_with_index do |err, index|
      fr = JSON.parse(err.data).with_indifferent_access
      fr[:errors] = JSON.parse(@errors[index].upload_errors)[0]
      @employees << fr
    end
  end

  def generate_csv
    # respond_to do |format|
      # format.html
      send_data @bulk_employee_upload.to_csv, filename: "upload-#{Date.today}.csv"
    # end
  end
  

  # POST /bulk_employee_uploads
  # POST /bulk_employee_uploads.json
  def create
    @bulk_employee_upload = BulkEmployeeUpload.new(bulk_employee_upload_params)
    # render json: @bulk_employee_upload
    # return
    respond_to do |format|
      if @bulk_employee_upload.save
        format.html { redirect_to @bulk_employee_upload, notice: 'Bulk employee file was successfully created.' }
        format.json { render :show, status: :created, location: @bulk_employee_upload }
      else
        format.html { render :new }
        format.json { render json: @bulk_employee_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bulk_employee_uploads/1
  # PATCH/PUT /bulk_employee_uploads/1.json
  def update
    respond_to do |format|
      if @bulk_employee_upload.update(bulk_employee_upload_params)
        format.html { redirect_to @bulk_employee_upload, notice: 'Bulk employee file was successfully updated.' }
        format.json { render :show, status: :ok, location: @bulk_employee_upload }
      else
        format.html { render :edit }
        format.json { render json: @bulk_employee_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bulk_employee_uploads/1
  # DELETE /bulk_employee_uploads/1.json
  def destroy
    @bulk_employee_upload.destroy
    respond_to do |format|
      format.html { redirect_to bulk_employee_uploads_url, notice: 'Bulk employee file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bulk_employee_upload
      @bulk_employee_upload = BulkEmployeeUpload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bulk_employee_upload_params
      params.require(:bulk_employee_upload).permit(:company_id, :file)
    end
end

app/helpers/bulk_employee_uploads_helper.rb
module BulkEmployeeUploadsHelper
end

app/views/bulk_employee_uploads/_form.html.erb
<%= form_with(model: bulk_employee_upload, local: true , :html => {:multipart => true}) do |form| %>
  <% if bulk_employee_upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bulk_employee_upload.errors.count, "error") %> prohibited this bulk_employee_upload from being saved:</h2>

      <ul>
      <% bulk_employee_upload.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company_id %>
    <%= form.collection_select(:company_id, Company.all, 'id', 'name', {:include_blank => 'Select Company'}) %>
  </div>
  <p>
  Please download a <a href="/samples/valid_sample.csv">sample file</a> from here please make sure you do not change the header in it.
  </p>
  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bulk_employee_uploads/edit.html.erb
<h1>Editing Bulk Employee File</h1>

<%= render 'form', bulk_employee_upload: @bulk_employee_upload %>

<%= link_to 'Show', @bulk_employee_upload %> |
<%= link_to 'Back', bulk_employee_uploads_path %>

app/views/bulk_employee_uploads/employees_index.erb
<p id="notice"><%= notice %></p>

<h1>Employees Uploaded With This CSV</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.company.name %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'back', @bulk_employee_upload %>

app/views/bulk_employee_uploads/errors_index.erb
<p id="notice"><%= notice %></p>

<h1>Employees Uploaded With This CSV</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Report to</th>
      <th>Assigned Policies</th>
      <th>Errors</th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee["employee_name"] %></td>
        <td><%= employee["email"] %></td>
        <td><%= employee["phone"] %></td>
        <td><%= employee["report_to"] %></td>
        <td><%= employee["assigend_policies"] %></td>
        <td><%= employee["errors"] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'back', @bulk_employee_upload %>
<%= link_to 'Generate CSV', generate_csv_bulk_employee_upload_path(@bulk_employee_upload.id) %>

app/views/bulk_employee_uploads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bulk Employee Files</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Upload File</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bulk_employee_uploads.each do |bulk_employee_upload| %>
      <tr>
        <td><%= bulk_employee_upload.company.name rescue "NA" %></td>
        <td><%= bulk_employee_upload.file.url %></td>
        <td><%= bulk_employee_upload.status %></td>
        <td><%= link_to 'Show', bulk_employee_upload %></td>
        <td><%= link_to 'Edit', edit_bulk_employee_upload_path(bulk_employee_upload) %></td>
        <td><%= link_to 'Destroy', bulk_employee_upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bulk Employee File', new_bulk_employee_upload_path %>

app/views/bulk_employee_uploads/new.html.erb
<h1>New Bulk Employee File</h1>

<%= render 'form', bulk_employee_upload: @bulk_employee_upload %>

<%= link_to 'Back', bulk_employee_uploads_path %>

app/views/bulk_employee_uploads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @bulk_employee_upload.company.name %>
</p>

<p>
  <strong>File:</strong>
  <%= @bulk_employee_upload.file.url %>
</p>

<p>
  <strong>Total: </strong>
  <strong id="total"><%= @total %></strong>
</p>

<p>
  <strong>Record Created: </strong>
  <strong id="created"><%= @employee_count %></strong>
  <%= link_to 'click here to know more details', employees_bulk_employee_upload_path(@bulk_employee_upload.id) %>
</p>

<p>
  <strong>Record Not Created(With Error): </strong>
  <strong id="errored"><%= @err_count %></strong>
  <%= link_to 'click here to know more errors details', errors_bulk_employee_upload_path(@bulk_employee_upload.id) %>
</p>

<%= link_to 'Edit', edit_bulk_employee_upload_path(@bulk_employee_upload) %> |
<%= link_to 'Back', bulk_employee_uploads_path %>